config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'regulars#index'
  
  resources :users, only: [:edit, :update]

  resources :regulars, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :persuations, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :traffics, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :costs, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :contracts, only: [:index, :new, :create, :show, :update, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :breakdowns, only: [:index, :show] do
    collection do
      get 'search'
      get 'check'
      get 'report'
    end
  end

  resources :settlements, only: [:index, :create, :show, :destroy]
  resources :closings, only: [:create, :show, :destroy]
end

app/models/persuation.rb
class Persuation < ApplicationRecord
  belongs_to :user
  has_many :persuation_contracts, dependent: :destroy
  has_many :contracts, through: :persuation_contracts, dependent: :destroy
  validates :dating, presence: true
  validates :hno, presence: true
  validates :contract_ids, presence: true

  def self.search(search)
    search_time = "#{search["dating(1i)"]}-#{search["dating(2i)"]}-01"
    Persuation.where(user_id: "#{search[:user_id]}").where(dating: search_time.in_time_zone.all_month)
  end

  def self.search_month(search)
    search_time = "#{search["dating(1i)"]}-#{search["dating(2i)"]}-01"
    Persuation.where(dating: search_time.in_time_zone.all_month)
  end
end

app/controllers/persuations_controller.rb
class PersuationsController < ApplicationController

  def new
    @persuation = Persuation.new
    @contracts = Contract.where(kind: "2").where(active: true)
  end

  def create
    @persuation = Persuation.new(persuation_params)
    if params[:persuation][:dating].present? && Closing.check(persuation_params).present?
      redirect_to root_path, alert: '申請済のため入力できません'
    elsif @persuation.save
      redirect_to root_path, notice: '調査費登録しました'
    else
      @contracts = Contract.where(kind: "2").where(active: true)
      render :new
    end
  end

  def show
    @persuation = Persuation.all
  end

  def destroy
    persuation = Persuation.find(params[:id])
    persuation.destroy
    redirect_to persuation_path, notice: "選んだ説得費を削除しました"
  end

  def search
    search_action(search_params)
  end

  def check
    if params[:user_id].present?
      @name = User.find(params[:user_id]).name
      search_action(params)
    else
      redirect_to breakdown_path(:id), alert: "ユーザーの選択がありません"
    end
  end

  private
  def persuation_params
    params.require(:persuation).permit(:dating, :hno, contract_ids: []).merge(user_id: current_user.id)
  end

  def search_params
    params.merge(user_id: current_user.id)
  end

  def search_action(params)
    @year = params["dating(1i)"]
    @month = params["dating(2i)"]
    @persuations = Persuation.search(params)
    @contracts = Contract.where(kind: "2")
  end
end

app/views/persuations/check.html.haml
.wrapper
  .Title
    説得費検索結果
  .Periodcenter
    .Periodcenter__content
      = "#{@name}さん"
      = "#{@year}年#{@month}月分"
  .Regular__show
    .Regular__show__table
      - if @persuations.present?
        %table{border: "1"}
          %tr
            %th.table_style
              日付
            %th.table_style
              HNO
            - @contracts.each do |contract|
              %th.table_style
                = contract.name
            %th.table_style
              削除ボタン
          - @persuations.each do |persuation|
            %tr
              %td.table_style
                = persuation.dating
              %td.table_style
                = persuation.hno
              - @contracts.each do |work|
                - if persuation.contracts.include?(work)
                  %th.table_style
                    = 1
                - else
                  %th.table_style
                    = 0
              %td.table_style
                = link_to '削除', "/persuations/#{persuation.id}", method: :delete, class:"btn btn-danger"
      - else
        該当の月はありません
  .Regular__return
    = link_to "戻る","/breakdowns/:id",class: 'btn-sized btn btn-secondary'

app/views/persuations/new.html.haml
.wrapper
  .Title
    説得費登録
  .Regular
    - if @persuation.errors.any?
      .Regular__errors
        .Regular__errors__content
          %h2= "#{@persuation.errors.full_messages.count}件のエラーが発生しました。"
          %ul
            - @persuation.errors.full_messages.each do |message|
              %li= message
    .Regular__table
      = form_with model: @persuation, local: true do |f|
        .Regular__table__content
          .Regular__table__content__tb
            %table{border: "1"}
              %tr
                %th.table_style
                  日付
                %th.table_style
                  HNO
                %th.table_style.text-aline
                  説得費
              %tr
                %td.table_style
                  = f.date_field :dating, use_month_numbers:true,prompt:"--", class: ''
                %td.table_style
                  = f.number_field :hno, min: 0,class:""
                %td.table_style.check_box
                  = f.collection_check_boxes :contract_ids, @contracts, :id, :name
        .Regular__table__btn
          .Regular__table__btn__content
            = f.submit '説得費登録', class: 'btn-lg btn btn-success'
    .Regular__return
      .Regular__return__btn
        = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'

app/views/persuations/search.html.haml
.wrapper
  .Title
    説得費検索結果
  .Periodcenter
    .Periodcenter__content
      = "#{@year}年#{@month}月分"
  .Regular__show
    .Regular__show__table
      - if @persuations.present?
        %table{border: "1"}
          %tr
            %th.table_style
              日付
            %th.table_style
              HNO
            - @contracts.each do |contract|
              %th.table_style
                = contract.name
            %th.table_style
              削除ボタン
          - @persuations.each do |persuation|
            %tr
              %td.table_style
                = persuation.dating
              %td.table_style
                = persuation.hno
              - @contracts.each do |work|
                - if persuation.contracts.include?(work)
                  %th.table_style
                    = 1
                - else
                  %th.table_style
                    = 0
              %td.table_style
                %button.btn.btn-danger{type: "button",data: {toggle: "modal", target: "#staticBackdrop#{persuation.id}"}}
                  削除
                .modal.fade{id: "staticBackdrop#{persuation.id}", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                  .modal-dialog
                    .modal-content
                      .modal-header
                        %h3.modal-title#staticBackdropLabel
                          確認
                        %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                          %span{aria:{hidden: "true"}}
                            &times;
                      .modal-body
                        %h5
                          本当に削除しますか？
                      .modal-footer
                        %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                          戻る
                        = link_to "削除", "/persuations/#{persuation.id}", method: :delete, class:"btn btn-danger btn-lg"
      - else
        該当の月はありません
  .Regular__return
    = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'

app/views/persuations/show.html.haml
.wrapper
  .Title
    説得費確認
  .Regular__form
    .Regular__form__content
      = form_with url: search_persuations_path, local: true, method: :get, class: "" do |f|
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style2'
        = "月"
        = f.submit "検索", class: "btn btn-info btn-lg"
  .Regular__return
    = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'