config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'regulars#index'
  
  resources :users, only: [:edit, :update]

  resources :regulars, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :persuations, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :traffics, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :costs, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :contracts, only: [:index, :new, :create, :show, :update, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :breakdowns, only: [:index, :show] do
    collection do
      get 'search'
      get 'check'
      get 'report'
    end
  end

  resources :settlements, only: [:index, :create, :show, :destroy]
  resources :closings, only: [:create, :show, :destroy]
end

app/controllers/breakdowns_controller.rb
class BreakdownsController < ApplicationController
  before_action :user_admin, only: [:show, :check]

  def index
  end

  def show
  end

  def search
    search_action(search_params)
  end

  def check
    if params[:user_id].present?
      @name = User.find(params[:user_id]).name
      search_action(params)
    else
      redirect_to breakdown_path(:id), alert: "ユーザーの選択がありません"
    end
  end

  def report
    @users = User.where(admin: false)
    @year = params["dating(1i)"]
    @month = params["dating(2i)"]

    @regulars = Regular.search_month(params)
    @persuations = Persuation.search_month(params)

    @contracts1 = Contract.where(kind: "1")
    @contracts2 = Contract.where(kind: "2")

    @traffics = Traffic.search_month(params)
    @costs = Cost.search_month(params)
  end

  private

  def search_action(params)
    @year = params["dating(1i)"]
    @month = params["dating(2i)"]

    @regulars = Regular.search(params)
    @persuations = Persuation.search(params)
    traffics = Traffic.search(params)
    costs = Cost.search(params)
    @contracts1 = Contract.where(kind: "1")
    @contracts2 = Contract.where(kind: "2")

    @amount_distance = 0
    @amount_fee = 0
    traffics.each do |traffic|
      @amount_distance += traffic.distance * 30 if traffic.distance?
      @amount_fee += traffic.fee if traffic.fee?
    end

    @amount_parking = 0
    @amount_fee2 = 0
    costs.each do |cost|
      @amount_parking += cost.parking if cost.parking?
      @amount_fee2 += cost.fee if cost.fee?
    end

    @userid = params[:user_id]
    @settlement2 = Settlement.search(params).where(settler: 2)
    @settlement3 = Settlement.search(params).where(settler: 3)
    @settlement4 = Settlement.search(params).where(settler: 4)

    @closing = Closing.search(params)
  end

  def search_params
    params.merge(user_id: current_user.id)
  end

  def user_admin
    unless current_user.admin?
      redirect_to root_path, alert: "管理の権限がありません"
    end
  end

end

app/views/breakdowns/_results.html.haml
.Breakdown-wrapper
  .Breakdown
    .Breakdown__show
      1.調査費
      %table{border: "1"}
        %tr
          %th.table_style
            
          - @contracts1.each do |contract|
            %th.table_style
              = contract.name
        %tr
          %th.table_style
            単価
          - @contracts1.each do |contract|
            %th.table_style
              = contract.money
        %tr
          %th.table_style
            件数
          - @contracts1.each do |contract|
            %th.table_style
              - count = 0
              - @regulars.each do |regular|
                - if regular.contracts.include?(contract)
                  - count += 1
              = count
        %tr
          %th.table_style
            単価×件数
          - bill = 0
          - @contracts1.each do |contract|
            %th.table_style
              - count = 0
              - @regulars.each do |regular|
                - if regular.contracts.include?(contract)
                  - count += 1
              - bill += count * contract.money
              = count * contract.money
    .Breakdown__amount
      %table{border: "2"}
        %tr
          %th.table_style
            調査費の小計
          %th.table_style
            = bill
        %tr
          %th.table_style
            調査費の消費税
          %th.table_style
            - tax = (bill * 0.1).floor
            = tax
        %tr
          %th.table_style
            調査費の合計
          %th.table_style
            - total1 = bill + tax
            = total1
  .Breakdown
    .Breakdown__show
      2.説得費
      %table{border: "1"}
        %tr
          %th.table_style
            
          - @contracts2.each do |contract|
            %th.table_style
              = contract.name
        %tr
          %th.table_style
            単価
          - @contracts2.each do |contract|
            %th.table_style
              = contract.money
        %tr
          %th.table_style
            件数
          - @contracts2.each do |contract|
            %th.table_style
              - count = 0
              - @persuations.each do |persuation|
                - if persuation.contracts.include?(contract)
                  - count += 1
              = count
        %tr
          %th.table_style
            単価×件数
          - bill = 0
          - @contracts2.each do |contract|
            %th.table_style
              - count = 0
              - @persuations.each do |persuation|
                - if persuation.contracts.include?(contract)
                  - count += 1
              - bill += count * contract.money
              = count * contract.money
    .Breakdown__amount
      %table{border: "2"}
        %tr
          %th.table_style
            説得費の小計
          %th.table_style
            = bill
        %tr
          %th.table_style
            説得費の消費税
          %th.table_style
            - tax = (bill * 0.1).floor
            = tax
        %tr
          %th.table_style
            説得費の合計
          %th.table_style
            - total2 = bill + tax
            = total2
  .Breakdownbottom
    .Breakdownbottom__traffic
      3.諸経費
      %table{border: "1"}
        %tr
          %th.table_style

          %th.table_style
            距離金額(km×30)
          %th.table_style
            運賃等
          %th.table_style
            通行費･駐車料
          %th.table_style
            消耗品
          %th.table_style
            合計
        %tr
          %th.table_style
            交通費･諸経費
          %th.table_style
            = @amount_distance
          %th.table_style
            = @amount_fee
          %th.table_style
            = @amount_parking
          %th.table_style
            = @amount_fee2
          %th.table_style
            - total3 = @amount_distance + @amount_fee + @amount_parking + @amount_fee2
            = total3
    .Breakdownbottom__amount
      %table{border: "2"}
        %tr
          %th.table_style
            総合計
          %th.table_style
            = total1 + total2 + total3

app/views/breakdowns/check.html.haml
.wrapper
  .Title
    内訳書
  .Period
    = "#{@name}さん"
    = "#{@year}年#{@month}月分"
  = render partial: "results", locals: { }
  .Undercontents
    .Undercontents__button
      = link_to "確認画面へ戻る","/breakdowns/:id", class: 'btn btn-lg btn-secondary Breakdownbottom__btn'
    .Undercontents__settlement
      %table{border: "1"}
        %tr
          %th.table_style
            担当者
          %th.table_style
            課長
          %th.table_style
            部長
        %tr
          %td.table_style.table_settlement
            - if @closing.empty?
              未申請
            - elsif @settlement4.present?
              .hanko
                担当
            - elsif current_user.id == 4
              %button.btn-lg.btn.btn-outline-danger{type: "button",data: {toggle: "modal", target: "#staticBackdrop"}}
                決済
              .modal.fade{id: "staticBackdrop", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                .modal-dialog
                  .modal-content
                    .modal-header
                      %h3.modal-title#staticBackdropLabel
                        確認
                      %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                        %span{aria:{hidden: "true"}}
                          &times;
                    .modal-body
                      %h5
                        本当に決済しますか？確認漏れはありませんか？
                    .modal-footer
                      %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                        戻る
                      = form_with url: settlements_path, local: true, method: :post do |f|
                        = f.hidden_field :dating, value: "#{@year}-#{@month}-01"
                        = f.hidden_field :user_id, value: @userid
                        = f.hidden_field :settler, value: current_user.id
                        = f.submit '決済', class: 'btn-lg btn btn-outline-danger'
            - else
          %td.table_style.table_settlement
            - if @closing.empty?
              未申請
            - elsif @settlement3.present?
              .hanko
                課長
            - elsif current_user.id == 3
              %button.btn-lg.btn.btn-outline-danger{type: "button",data: {toggle: "modal", target: "#staticBackdrop"}}
                決済
              .modal.fade{id: "staticBackdrop", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                .modal-dialog
                  .modal-content
                    .modal-header
                      %h3.modal-title#staticBackdropLabel
                        確認
                      %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                        %span{aria:{hidden: "true"}}
                          &times;
                    .modal-body
                      %h5
                        本当に決済しますか？確認漏れはありませんか？
                    .modal-footer
                      %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                        戻る
                      = form_with url: settlements_path, local: true, method: :post do |f|
                        = f.hidden_field :dating, value: "#{@year}-#{@month}-01"
                        = f.hidden_field :user_id, value: @userid
                        = f.hidden_field :settler, value: current_user.id
                        = f.submit '決済', class: 'btn-lg btn btn-outline-danger'
            - else

          %td.table_style.table_settlement
            - if @closing.empty?
              未申請
            - elsif @settlement2.present?
              .hanko
                部長
            - elsif current_user.id == 2
              %button.btn-lg.btn.btn-outline-danger{type: "button",data: {toggle: "modal", target: "#staticBackdrop"}}
                決済
              .modal.fade{id: "staticBackdrop", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                .modal-dialog
                  .modal-content
                    .modal-header
                      %h3.modal-title#staticBackdropLabel
                        確認
                      %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                        %span{aria:{hidden: "true"}}
                          &times;
                    .modal-body
                      %h5
                        本当に決済しますか？確認漏れはありませんか？
                    .modal-footer
                      %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                        戻る
                      = form_with url: settlements_path, local: true, method: :post do |f|
                        = f.hidden_field :dating, value: "#{@year}-#{@month}-01"
                        = f.hidden_field :user_id, value: @userid
                        = f.hidden_field :settler, value: current_user.id
                        = f.submit '決済', class: 'btn-lg btn btn-outline-danger'
            - else

app/views/breakdowns/index.html.haml
.wrapper
  .Title
    MY内訳書確認
  .Regular__form
    .Regular__form__content
      = form_with url: search_breakdowns_path, local: true, method: :get, class: "" do |f|
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style2'
        = "月"
        = f.submit "内訳検索", class: "btn btn-lg btn-info"
  .Regular__return
    .Regular__return__btn
      = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'

app/views/breakdowns/report.html.haml
.wrapper
  .Title
    帳票表示
  .Periodcenter
    .Periodcenter__content
      = "#{@year}年#{@month}月分"
  .Regular__show
    .Regular__show__table
      %table{border: "1"}
        %tr
          %th.table_style.table_closing
            コミュニケーター
          %th.table_style
            調査費
          %th.table_style
            説得費
          %th.table_style
            諸経費
          %th.table_style.table_red
            総合計
        - @users.each do |user|
          %tr
            %td.table_style.table_closing
              = user.name
            %td.table_style
              - bill1 = 0
              - @regulars.each do |regular| #ユーザーも契約も混合したものを取り出す
                - if regular.user_id == user.id #このユーザーが登録したレコードを抜き出す
                  - @contracts1.each do |contract| #複数の契約を契約ごとに金額足す
                    - if regular.contracts.include?(contract)
                      - bill1 += contract.money
              = bill1 = bill1 + (bill1 * 0.1).floor
            %td.table_style
              - bill2 = 0
              - @persuations.each do |persuation| 
                - if persuation.user_id == user.id 
                  - @contracts2.each do |contract|
                    - if persuation.contracts.include?(contract)
                      - bill2 += contract.money
              = bill2 = bill2 + (bill2 * 0.1).floor
            %td.table_style
              - @amount_distance = 0
              - @amount_fee = 0
              - @traffics.each do |traffic|
                - if traffic.user_id == user.id
                  - @amount_distance += traffic.distance * 30 if traffic.distance?
                  - @amount_fee += traffic.fee if traffic.fee?
              - @amount_parking = 0
              - @amount_fee2 = 0
              - @costs.each do |cost|
                - if cost.user_id == user.id
                  - @amount_parking += cost.parking if cost.parking?
                  - @amount_fee2 += cost.fee if cost.fee?
              = bill3 = @amount_distance + @amount_fee + @amount_parking + @amount_fee2
            %td.table_style.table_red
              = bill1 + bill2 + bill3
  .Regular__return
    = link_to "戻る","/breakdowns/:id",class: 'btn-lg btn btn-secondary'

app/views/breakdowns/search.html.haml
.wrapper
  .Title
    内訳書
  .Period
    = "#{@year}年#{@month}月分"
  = render partial: "results", locals: { }
  .Undercontents
    .Undercontents__button
      = link_to "戻る","/breakdowns", class: 'btn btn-lg btn-secondary Breakdownbottom__btn'
    .Undercontents__settlement
      %table{border: "1"}
        %tr
          %th.table_style
            締め申請
        %tr
          %td.table_style.table_settlement
            - if @closing.present?
              .hanko_closing
                申請済
            - else
              %buttonbtn-lg.btn.btn-outline-danger{type: "button",data: {toggle: "modal", target: "#staticBackdrop"}}
                締め申請
              .modal.fade{id: "staticBackdrop", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                .modal-dialog
                  .modal-content
                    .modal-header
                      %h3.modal-title#staticBackdropLabel
                        確認
                      %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                        %span{aria:{hidden: "true"}}
                          &times;
                    .modal-body
                      %h5
                        本当に締め申請しますか？申請後は訂正できません。
                    .modal-footer
                      %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                        戻る
                      = form_with url: closings_path, local: true, method: :post do |f|
                        = f.hidden_field :dating, value: "#{@year}-#{@month}-01"
                        = f.hidden_field :user_id, value: current_user.id
                        = f.submit '締め申請', class: 'btn-lg btn btn-outline-danger'
                

app/views/breakdowns/show.html.haml
.wrapper
  .Title
    内訳･詳細表示
  .Regular__form
    .Regular__form__content
      .Regular__form__content__settlement
        .Regular__form__content__settlement__check
          ■決済はコチラからです
          = form_with url: check_breakdowns_path, local: true, method: :get, class: "" do |f|
            = f.label "コミュニケーター"
            = f.collection_select(:user_id, User.where(admin: false), :id, :name, {prompt: true}, {class:"table_style"})
            = f.label "時期"
            = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style'
            = "月"
            = f.submit "内訳書検索", class: "btn btn-lg btn-outline-danger"
        .Regular__form__content__settlement__check
          ■帳票確認はコチラからです(コミュニケーター指定は不要です)
          = form_with url: report_breakdowns_path, local: true, method: :get, class: "" do |f|
            = f.label "コミュニケーター"
            = f.collection_select(:user_id, User.where(admin: false), :id, :name, {prompt: "指定しないでよい"}, {class:"table_style"})
            = f.label "時期"
            = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style'
            = "月"
            = f.submit "月総額検索", class: "btn btn-lg btn-outline-info"
    .Regular__form__content
      = form_with url: check_regulars_path, local: true, method: :get, class: "" do |f|
        = f.label "コミュニケーター"
        = f.collection_select(:user_id, User.where(admin: false), :id, :name, {prompt: true}, {class:"table_style"})
        = f.label "時期"
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style'
        = "月"
        = f.submit "調査費検索", class: "btn btn-lg btn-danger"
    .Regular__form__content
      = form_with url: check_persuations_path, local: true, method: :get, class: "" do |f|
        = f.label "コミュニケーター"
        = f.collection_select(:user_id, User.where(admin: false), :id, :name, {prompt: true}, {class:"table_style"})
        = f.label "時期"
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style'
        = "月"
        = f.submit "説得費検索", class: "btn btn-lg btn-warning"
    .Regular__form__content
      = form_with url: check_traffics_path, local: true, method: :get, class: "" do |f|
        = f.label "コミュニケーター"
        = f.collection_select(:user_id, User.where(admin: false), :id, :name, {prompt: true}, {class:"table_style"})
        = f.label "時期"
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style'
        = "月"
        = f.submit "交通費検索", class: "btn btn-lg btn-success"
    .Regular__form__content
      = form_with url: check_costs_path, local: true, method: :get, class: "" do |f|
        = f.label "コミュニケーター"
        = f.collection_select(:user_id, User.where(admin: false), :id, :name, {prompt: true}, {class:"table_style"})
        = f.label "時期"
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style'
        = "月"
        = f.submit "諸経費検索", class: "btn btn-lg btn-info"
  .Regular__return
    = link_to "管理画面へ戻る","/contracts",class: 'btn-lg btn btn-secondary'