config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'regulars#index'
  
  resources :users, only: [:edit, :update]

  resources :regulars, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :persuations, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :traffics, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :costs, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :contracts, only: [:index, :new, :create, :show, :update, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :breakdowns, only: [:index, :show] do
    collection do
      get 'search'
      get 'check'
      get 'report'
    end
  end

  resources :settlements, only: [:index, :create, :show, :destroy]
  resources :closings, only: [:create, :show, :destroy]
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  
  validates :dating, presence: true
  validates :hno, presence: true

  def self.search(search)
    search_time = "#{search["dating(1i)"]}-#{search["dating(2i)"]}-01"
    Cost.where(user_id: "#{search[:user_id]}").where(dating: search_time.in_time_zone.all_month)
  end

  def self.search_month(search)
    search_time = "#{search["dating(1i)"]}-#{search["dating(2i)"]}-01"
    Cost.where(dating: search_time.in_time_zone.all_month)
  end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController

  def new
    @cost = Cost.new
    @cost.images.new
  end

  def create
    @cost = Cost.new(cost_params)
    if params[:cost][:dating].present? && Closing.check(cost_params).present?
      redirect_to root_path, alert: '申請済のため入力できません'
    elsif @cost.save
      redirect_to root_path, notice: '諸経費登録しました'
    else
      render :new
    end
  end

  def show
    @cost = Cost.all
  end

  def destroy
    cost = Cost.find(params[:id])
    cost.destroy
    redirect_to cost_path, notice: "選んだ諸経費を削除しました"
  end

  def search
    search_action(search_params)
  end

  def check
    if params[:user_id].present?
      @name = User.find(params[:user_id]).name
      search_action(params)
    else
      redirect_to breakdown_path(:id), alert: "ユーザーの選択がありません"
    end
  end

  private
  def cost_params
    params.require(:cost).permit(:dating, :hno, :parking, :fee, :content, images_attributes: [:src]).merge(user_id: current_user.id)
  end

  def search_params
    params.merge(user_id: current_user.id)
  end

  def search_action(params)
    @year = params["dating(1i)"]
    @month = params["dating(2i)"]
    @costs = Cost.search(params)
  end
end

app/views/costs/_image_form.html.haml
.Listing__Main__ListingImage
  .Listing__Main__ListingImage__title
    諸経費のレシート等画像(最大3枚まで)
  .Listing__Main__ListingImage__picture
    #image-box
      .previews
        = f.fields_for :images do |image|
          = image.label :src ,class: "Listing__Main__ListingImage__picture__field" do
            .js-file_group{data: {index: image.index}}
              = image.file_field :src, class: "file-field js-file"
              こちらをクリックして画像アップロードしてください

app/views/costs/check.html.haml
.wrapper
  .Title
    諸経費検索結果
  .Periodcenter
    .Periodcenter__content
      = "#{@name}さん"
      = "#{@year}年#{@month}月分"
  .Regular__show
    .Regular__show__table
      - if @costs.present?
        %table{border: "1"}
          %tr
            %th.table_style
              日付
            %th.table_style
              HNO
            %th.table_style
              通行費･駐車料
            %th.table_style
              通信費･消耗品費
            %th.table_style
              内訳詳細
            %th.table_style
              削除ボタン
          - @costs.each do |cost|
            %tr
              %td.table_style
                = cost.dating
              %td.table_style
                = cost.hno
              %td.table_style
                = cost.parking
              %td.table_style
                = cost.fee
              %td.table_style
                = cost.content
              %td.table_style
                = link_to '削除', "/costs/#{cost.id}", method: :delete, class:"btn btn-danger"
      - else
        該当の月はありません
  .Regular__return
    = link_to "戻る","/breakdowns/:id",class: 'btn-sized btn btn-secondary'

app/views/costs/new.html.haml
.wrapper
  .Title
    諸経費登録
  .Regular
    - if @cost.errors.any?
      .Regular__errors
        .Regular__errors__content
          %h2= "#{@cost.errors.full_messages.count}件のエラーが発生しました。"
          %ul
            - @cost.errors.full_messages.each do |message|
              %li= message
    .Regular__table
      = form_with model: @cost, local: true do |f|
        .Regular__table__content
          .Regular__table__content__tb
            %table{border: "1"}
              %tr
                %th.table_style
                  日付
                %th.table_style
                  HNO
                %th.table_style
                  通行費･駐車料
                %th.table_style
                  通信費･消耗品費
                %th.table_style
                  内訳詳細
              %tr
                %td.table_style
                  = f.date_field :dating, use_month_numbers:true,prompt:"--", class: ''
                %td.table_style
                  = f.number_field :hno, min: 0,class:""
                %td.table_style
                  = f.number_field :parking, min: 0, class:""
                %td.table_style
                  = f.number_field :fee, min: 0,step:"0.1",class:""
                %td.table_style
                  = f.text_field :content, class:""
        .Regular__table__image
          = render partial: "image_form", locals: { f: f, cost: @cost}
        .Regular__table__btn
          .Regular__table__btn__content
            = f.submit '諸経費登録', class: 'btn-lg btn btn-success'
    .Regular__return
      = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'

app/views/costs/search.html.haml
.wrapper
  .Title
    諸経費検索結果
  .Periodcenter
    .Periodcenter__content
      = "#{@year}年#{@month}月分"
  .Regular__show
    .Regular__show__table
      - if @costs.present?
        %table{border: "1"}
          %tr
            %th.table_style
              日付
            %th.table_style
              HNO
            %th.table_style
              通行費･駐車料
            %th.table_style
              通信費･消耗品費
            %th.table_style
              内訳詳細
            %th.table_style
              画像確認
            %th.table_style
              削除ボタン
          - @costs.each do |cost|
            %tr
              %td.table_style
                = cost.dating
              %td.table_style
                = cost.hno
              %td.table_style
                = cost.parking
              %td.table_style
                = cost.fee
              %td.table_style
                = cost.content
              %td.table_style
                - if cost.images.present?
                  %button.btn.btn-secondary{type: "button",data: {toggle: "modal", target: "#staticBackdrop#{cost.id}image"}}
                    確認
                  .modal.fade{id: "staticBackdrop#{cost.id}image", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                    .modal-dialog
                      .modal-content.modal-image-content
                        .modal-header
                          %h3.modal-title#staticBackdropLabel.modal-image-title
                            諸経費画像
                          %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                            %span{aria:{hidden: "true"}}
                              &times;
                        .modal-body
                          .modal-previews
                            - cost.images.each_with_index do |image, i|
                              .preview
                                .img_box{data: {index: i }}
                                  = image_tag "#{image.src.url}", data: { index: i }, class: "preview_image_modal"
                    
                        .modal-footer
                          %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                            戻る
              %td.table_style
                %button.btn.btn-danger{type: "button",data: {toggle: "modal", target: "#staticBackdrop#{cost.id}"}}
                  削除
                .modal.fade{id: "staticBackdrop#{cost.id}", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                  .modal-dialog
                    .modal-content
                      .modal-header
                        %h3.modal-title#staticBackdropLabel
                          確認
                        %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                          %span{aria:{hidden: "true"}}
                            &times;
                      .modal-body
                        %h5
                          本当に削除しますか？
                      .modal-footer
                        %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                          戻る
                        = link_to "削除", "/costs/#{cost.id}", method: :delete, class:"btn btn-danger btn-lg"
                        
      - else
        該当の月はありません
  .Regular__return
    = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'

app/views/costs/show.html.haml
.wrapper
  .Title
    諸経費確認
  .Regular__form
    .Regular__form__content
      = form_with url: search_costs_path, local: true, method: :get, class: "" do |f|
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style2'
        = "月"
        = f.submit "検索", class: "btn btn-info btn-lg"
  .Regular__return
    = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'