config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'regulars#index'
  
  resources :users, only: [:edit, :update]

  resources :regulars, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :persuations, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :traffics, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :costs, only: [:new, :create, :show, :destroy] do
    collection do
      get 'search'
      get 'check'
    end
  end

  resources :contracts, only: [:index, :new, :create, :show, :update, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :breakdowns, only: [:index, :show] do
    collection do
      get 'search'
      get 'check'
      get 'report'
    end
  end

  resources :settlements, only: [:index, :create, :show, :destroy]
  resources :closings, only: [:create, :show, :destroy]
end

app/models/traffic.rb
class Traffic < ApplicationRecord
  belongs_to :user
  validates :dating, presence: true
  validates :hno, presence: true

  def self.search(search)
    search_time = "#{search["dating(1i)"]}-#{search["dating(2i)"]}-01"
    Traffic.where(user_id: "#{search[:user_id]}").where(dating: search_time.in_time_zone.all_month)
  end

  def self.search_month(search)
    search_time = "#{search["dating(1i)"]}-#{search["dating(2i)"]}-01"
    Traffic.where(dating: search_time.in_time_zone.all_month)
  end
end

app/controllers/traffics_controller.rb
class TrafficsController < ApplicationController

  def new
    @traffic = Traffic.new
  end

  def create
    @traffic = Traffic.new(traffic_params)
    if params[:traffic][:dating].present? && Closing.check(traffic_params).present?
      redirect_to root_path, alert: '申請済のため入力できません'
    elsif @traffic.save
      redirect_to root_path, notice: '交通費登録しました'
    else
      render :new
    end
  end

  def show
    @traffic = Traffic.all
  end

  def destroy
    traffic = Traffic.find(params[:id])
    traffic.destroy
    redirect_to traffic_path, notice: "選んだ交通費を削除しました"
  end

  def search
    search_action(search_params)
  end

  def check
    if params[:user_id].present?
      @name = User.find(params[:user_id]).name
      search_action(params)
    else
      redirect_to breakdown_path(:id), alert: "ユーザーの選択がありません"
    end
  end

  private
  def traffic_params
    params.require(:traffic).permit(:dating, :hno, :field, :distance, :fee, :content).merge(user_id: current_user.id)
  end

  def search_params
    params.merge(user_id: current_user.id)
  end

  def search_action(params)
    @year = params["dating(1i)"]
    @month = params["dating(2i)"]
    @traffics = Traffic.search(params)
  end
end

app/views/traffics/check.html.haml
.wrapper
  .Title
    交通費検索結果
  .Periodcenter
    .Periodcenter__content
      = "#{@name}さん"
      = "#{@year}年#{@month}月分"
  .Regular__show
    .Regular__show__table
      - if @traffics.present?
        %table{border: "1"}
          %tr
            %th.table_style
              日付
            %th.table_style
              HNO
            %th.table_style
              方面、区間
            %th.table_style
              走行距離(km)
            %th.table_style
              交通料金(円)
            %th.table_style
              詳細
            %th.table_style
              削除ボタン
          - @traffics.each do |traffic|
            %tr
              %td.table_style
                = traffic.dating
              %td.table_style
                = traffic.hno
              %td.table_style
                = traffic.field
              %td.table_style
                = traffic.distance
              %td.table_style
                = traffic.fee
              %td.table_style
                = traffic.content
              %td.table_style
                = link_to '削除', "/traffics/#{traffic.id}", method: :delete, class:"btn btn-danger"
      - else
        該当の月はありません
  .Regular__return
    = link_to "戻る","/breakdowns/:id",class: 'btn-sized btn btn-secondary'

app/views/traffics/new.html.haml
.wrapper
  .Title
    交通費登録
  .Regular
    - if @traffic.errors.any?
      .Regular__errors
        .Regular__errors__content
          %h2= "#{@traffic.errors.full_messages.count}件のエラーが発生しました。"
          %ul
            - @traffic.errors.full_messages.each do |message|
              %li= message
    .Regular__table
      = form_with model: @traffic, local: true do |f|
        .Regular__table__content
          .Regular__table__content__tb
            %table{border: "1"}
              %tr
                %th.table_style
                  日付
                %th.table_style
                  HNO
                %th.table_style
                  方面、区間
                %th.table_style
                  走行距離(km)
                %th.table_style
                  交通料金(円)
                %th.table_style
                  詳細
              %tr
                %td.table_style
                  = f.date_field :dating, use_month_numbers:true,prompt:"--", class: ''
                %td.table_style
                  = f.number_field :hno, min: 0,class:""
                %td.table_style
                  = f.text_field :field, class:""
                %td.table_style
                  = f.number_field :distance, min: 0,step:"0.1",class:""
                %td.table_style
                  = f.number_field :fee, min: 0,class:""
                %td.table_style
                  = f.text_field :content, class:""
        .Regular__table__btn
          .Regular__table__btn__content
            = f.submit '交通費登録', class: 'btn-lg btn btn-success'
    .Regular__return
      .Regular__return__btn
        = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'

app/views/traffics/search.html.haml
.wrapper
  .Title
    交通費検索結果
  .Periodcenter
    .Periodcenter__content
      = "#{@year}年#{@month}月分"
  .Regular__show
    .Regular__show__table
      - if @traffics.present?
        %table{border: "1"}
          %tr
            %th.table_style
              日付
            %th.table_style
              HNO
            %th.table_style
              方面、区間
            %th.table_style
              走行距離(km)
            %th.table_style
              交通料金(円)
            %th.table_style
              詳細
            %th.table_style
              削除ボタン
          - @traffics.each do |traffic|
            %tr
              %td.table_style
                = traffic.dating
              %td.table_style
                = traffic.hno
              %td.table_style
                = traffic.field
              %td.table_style
                = traffic.distance
              %td.table_style
                = traffic.fee
              %td.table_style
                = traffic.content
              %td.table_style
                %button.btn.btn-danger{type: "button",data: {toggle: "modal", target: "#staticBackdrop#{traffic.id}"}}
                  削除
                .modal.fade{id: "staticBackdrop#{traffic.id}", data: {backdrop: "static", keyboard: "false"}, tabindex: "-1",aria:{labelledby: "staticBackdropLabel", hidden: "true"}}
                  .modal-dialog
                    .modal-content
                      .modal-header
                        %h3.modal-title#staticBackdropLabel
                          確認
                        %button.close{type:"button", data:{dismiss: "modal"}, aria:{label: "Close"}}
                          %span{aria:{hidden: "true"}}
                            &times;
                      .modal-body
                        %h5
                          本当に削除しますか？
                      .modal-footer
                        %button.btn.btn-lg.btn-secondary.btn-default{type:'button', data:{dismiss:'modal'}}
                          戻る
                        = link_to "削除", "/traffics/#{traffic.id}", method: :delete, class:"btn btn-danger btn-lg"
                
      - else
        該当の月はありません
  .Regular__return
    = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'

app/views/traffics/show.html.haml
.wrapper
  .Title
    交通費確認
  .Regular__form
    .Regular__form__content
      = form_with url: search_traffics_path, local: true, method: :get, class: "" do |f|
        = f.date_select :dating, {discard_day:true,use_month_numbers:true, date_separator:'年'}, class: 'table_style2' 
        = "月"
        = f.submit "検索", class: "btn btn-info btn-lg"
  .Regular__return
    = link_to "戻る","/regulars",class: 'btn-lg btn btn-secondary'